groupName: acme.nexus.fudo.org

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: igrnt/cert-manager-webhook-nexus
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
