groupName: nexus.fudo.org

replicaCount: 1

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: fudoniten/cert-manager-webhook-nexus
  tag: v1.0.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
