groupName: nexus.fudo.org

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: hub.docker.com/v2/fudoniten/cert-manager-webhook-nexus
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
